services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - node
    entrypoint: /bin/sh -c "until curl -s http://node:3000 > /dev/null; do echo waiting for node; sleep 3; done; nginx -g 'daemon off;'"
    networks:
      - app-network

  node:
    build: 
      context: ./node
    container_name: node-container
    environment:
      - DB_HOST=mysql-container
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=people_db
    tty: true
    volumes: 
      - node:/usr/src/app
    networks:
      - app-network
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=people_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    tty: true
    networks:
      - app-network

volumes:
  node:
  mysql-data:

networks:
  app-network:
    driver: bridge
    name: app-network
